FROM node:23-alpine AS build

WORKDIR /usr/src/app

COPY package*.json .
RUN npm install

COPY . .
RUN npm run build

FROM node:23-alpine AS production

WORKDIR /usr/src/app

COPY package*.json .
RUN npm install --only=production

COPY --from=build /usr/src/app/dist ./dist

CMD ["node", "dist/index.js"]